CFLAGS=-Wall -g

clean:
	rm -f ex1
	rm -f ex3
	rm -f ex4
	rm -f ex5
	rm -f ex6
	rm -f ex7
	rm -f ex8
	rm -f ex9
	rm -f ex10
	rm -f ex11
	rm -f ex12
	rm -f ex13
all:
	cc ex1.c	-o ex1
	cc ex3.c	-o ex3
	cc ex4.c	-o ex4
	cc ex5.c	-o ex5
	cc ex6.c	-o ex6
	cc ex7.c	-o ex7
	cc ex8.c	-o ex8
	cc ex9.c	-o ex9
	cc ex10.c	-o ex10
	cc ex11.c	-o ex11
	cc ex12.c	-o ex12
	cc ex13.c	-o ex13
